import { CrmEntity } from "./types";

export const SAMPLE_CRM_ENTITIES: CrmEntity[] = [
  // Projects
  {
    id: "p1",
    type: "project",
    name: "Austin Office Tower",
    subtitle: "Discovery · $45M · Commercial",
    data: {
      name: "Austin Office Tower",
      contractValue: 45000000,
      stage: "Discovery",
      company: "Turner Construction",
      division: "Commercial",
      gsf: 280000,
      stories: 12,
      constructionType: "New Construction",
      address: "200 Congress Ave",
      city: "Austin",
      state: "TX",
      marketSector: "Commercial Office",
      deliveryMethod: "CM at Risk",
      projectDuration: 24,
      constructionStart: "2024-09-01",
      constructionEnd: "2026-09-01",
      projectFeatures: "Class A office, LEED Gold target, structured parking, ground-floor retail",
    },
  },
  {
    id: "p2",
    type: "project",
    name: "Dell Medical Center Expansion",
    subtitle: "Bidding · $120M · Healthcare",
    data: {
      name: "Dell Medical Center Expansion",
      contractValue: 120000000,
      stage: "Bidding",
      company: "Seton Healthcare",
      division: "Commercial",
      gsf: 450000,
      stories: 8,
      constructionType: "Addition",
      address: "1601 Trinity St",
      city: "Austin",
      state: "TX",
      marketSector: "Healthcare",
      deliveryMethod: "Design-Build",
      projectDuration: 36,
      constructionStart: "2025-01-15",
      constructionEnd: "2028-01-15",
      projectFeatures: "Patient tower addition, surgical suites, imaging center, helipad, ICRA compliance",
    },
  },
  {
    id: "p3",
    type: "project",
    name: "Samsung Fab Retrofit",
    subtitle: "Proposal Sent · $85M · Industrial",
    data: {
      name: "Samsung Fab Retrofit",
      contractValue: 85000000,
      stage: "Proposal Sent",
      company: "Samsung Austin",
      division: "Industrial",
      gsf: 320000,
      constructionType: "Renovation",
      address: "12100 Samsung Blvd",
      city: "Austin",
      state: "TX",
      marketSector: "Industrial / Manufacturing",
      deliveryMethod: "CM at Risk",
      projectDuration: 18,
      projectFeatures: "Cleanroom retrofit, MEP upgrades, vibration-sensitive equipment, phased occupied renovation",
    },
  },
  {
    id: "p4",
    type: "project",
    name: "Domain Mixed-Use Phase III",
    subtitle: "Discovery · $62M · Mixed-Use",
    data: {
      name: "Domain Mixed-Use Phase III",
      contractValue: 62000000,
      stage: "Discovery",
      company: "Endeavor Real Estate",
      division: "Commercial",
      gsf: 380000,
      stories: 6,
      units: 285,
      constructionType: "New Construction",
      address: "11600 Domain Dr",
      city: "Austin",
      state: "TX",
      marketSector: "Mixed-Use",
      deliveryMethod: "Design-Build",
      projectDuration: 28,
      projectFeatures: "Residential over retail, structured parking, amenity deck, pool, fitness center",
    },
  },
  {
    id: "p5",
    type: "project",
    name: "The Grove at Shoal Creek",
    subtitle: "In Construction · $95M · Residential",
    data: {
      name: "The Grove at Shoal Creek",
      contractValue: 95000000,
      stage: "In Construction",
      company: "Milestone Community",
      division: "Residential-Custom",
      gsf: 520000,
      units: 478,
      stories: 5,
      constructionType: "New Construction",
      address: "3000 Shoal Creek Blvd",
      city: "Austin",
      state: "TX",
      marketSector: "Residential - Multi-Family",
      deliveryMethod: "CM at Risk",
      projectDuration: 30,
      constructionStart: "2024-03-01",
      constructionEnd: "2026-09-01",
      projectFeatures: "Luxury apartments, townhomes, community park, retail village, sustainability features",
    },
  },
  {
    id: "p6",
    type: "project",
    name: "UT Engineering Building",
    subtitle: "Contract Sent · $72M · Education",
    data: {
      name: "UT Engineering Building",
      contractValue: 72000000,
      stage: "Contract Sent",
      company: "University of Texas",
      division: "Commercial",
      gsf: 200000,
      stories: 5,
      constructionType: "New Construction",
      address: "2501 Speedway",
      city: "Austin",
      state: "TX",
      marketSector: "Education",
      deliveryMethod: "CM at Risk",
      projectDuration: 24,
      projectFeatures: "Research labs, lecture halls, maker spaces, collaboration areas, LEED Platinum target",
    },
  },

  // Leads
  {
    id: "l1",
    type: "lead",
    name: "City Hall Renovation",
    subtitle: "Contract Sent · $28M · Government",
    data: {
      name: "City Hall Renovation",
      value: 28000000,
      status: "OPEN",
      company: "City of Austin",
      gsf: 120000,
      source: "RFQ Response",
      address: "301 W 2nd St",
      city: "Austin",
      state: "TX",
      marketSector: "Government",
      deliveryMethod: "Design-Bid-Build",
      constructionDuration: 18,
    },
  },
  {
    id: "l2",
    type: "lead",
    name: "Tesla Gigafactory Warehouse",
    subtitle: "Discovery · $35M · Industrial",
    data: {
      name: "Tesla Gigafactory Warehouse",
      value: 35000000,
      status: "OPEN",
      company: "Tesla Inc",
      gsf: 500000,
      source: "Direct Contact",
      address: "13101 Harold Green Rd",
      city: "Austin",
      state: "TX",
      marketSector: "Industrial",
      deliveryMethod: "Design-Build",
      constructionDuration: 12,
    },
  },
  {
    id: "l3",
    type: "lead",
    name: "UT Stadium Expansion",
    subtitle: "Bidding · $200M · Education/Sports",
    data: {
      name: "UT Stadium Expansion",
      value: 200000000,
      status: "OPEN",
      company: "University of Texas",
      gsf: 350000,
      source: "Invitation to Bid",
      address: "2100 San Jacinto Blvd",
      city: "Austin",
      state: "TX",
      marketSector: "Education",
      deliveryMethod: "CM at Risk",
      constructionDuration: 30,
    },
  },
  {
    id: "l4",
    type: "lead",
    name: "Whole Foods HQ Remodel",
    subtitle: "Proposal Sent · $15M · Commercial",
    data: {
      name: "Whole Foods HQ Remodel",
      value: 15000000,
      status: "OPEN",
      company: "Whole Foods Market",
      gsf: 85000,
      source: "Referral",
      address: "550 Bowie St",
      city: "Austin",
      state: "TX",
      marketSector: "Commercial Office",
      deliveryMethod: "Negotiated GMP",
      constructionDuration: 10,
    },
  },

  // Companies
  {
    id: "c1",
    type: "company",
    name: "Turner Construction",
    subtitle: "Client · Construction",
    data: {
      name: "Turner Construction",
      category: "Client",
      address: "500 W 5th St",
      city: "Austin",
      state: "TX",
      website: "turnerconstruction.com",
      description: "One of the largest construction management companies in the US with extensive commercial and institutional portfolio.",
      industries: "Commercial, Healthcare, Education",
    },
  },
  {
    id: "c2",
    type: "company",
    name: "Seton Healthcare",
    subtitle: "Client · Healthcare",
    data: {
      name: "Seton Healthcare Family",
      category: "Client",
      address: "1201 W 38th St",
      city: "Austin",
      state: "TX",
      website: "seton.net",
      description: "Central Texas' largest healthcare network with multiple hospitals and clinics across the region.",
      industries: "Healthcare",
    },
  },
  {
    id: "c3",
    type: "company",
    name: "City of Austin",
    subtitle: "Client · Government",
    data: {
      name: "City of Austin",
      category: "Client",
      address: "301 W 2nd St",
      city: "Austin",
      state: "TX",
      website: "austintexas.gov",
      description: "Municipal government with ongoing capital improvement programs across facilities, parks, and infrastructure.",
      industries: "Government, Infrastructure",
    },
  },
  {
    id: "c4",
    type: "company",
    name: "University of Texas at Austin",
    subtitle: "Client · Education",
    data: {
      name: "University of Texas at Austin",
      category: "Client",
      address: "110 Inner Campus Dr",
      city: "Austin",
      state: "TX",
      website: "utexas.edu",
      description: "Flagship public university with extensive campus construction program including research, academic, and athletic facilities.",
      industries: "Education, Research",
    },
  },
  {
    id: "c5",
    type: "company",
    name: "Endeavor Real Estate",
    subtitle: "Client · Real Estate Development",
    data: {
      name: "Endeavor Real Estate Group",
      category: "Client",
      address: "6500 River Place Blvd",
      city: "Austin",
      state: "TX",
      website: "endeavor-re.com",
      description: "Leading Austin-based real estate firm specializing in mixed-use, office, and retail developments including The Domain.",
      industries: "Commercial, Mixed-Use, Retail",
    },
  },
  {
    id: "c6",
    type: "company",
    name: "Gensler",
    subtitle: "Design · Architecture",
    data: {
      name: "Gensler",
      category: "Design",
      address: "221 W 6th St",
      city: "Austin",
      state: "TX",
      website: "gensler.com",
      description: "Global architecture and design firm with expertise in workplace, mixed-use, and hospitality projects.",
      industries: "Architecture, Interior Design",
    },
  },
];

export function searchCrmEntities(query: string): CrmEntity[] {
  const q = query.toLowerCase();
  return SAMPLE_CRM_ENTITIES.filter(
    (e) =>
      e.name.toLowerCase().includes(q) ||
      e.subtitle?.toLowerCase().includes(q) ||
      e.type.includes(q)
  );
}
